### PR TITLE
A quick fix for the player inventory opening.

### PR DESCRIPTION
**Pull request by vini2003**
It's a quick fix for an immediate necessity, but works.

Do as you wish!

### CODE REVIEW

**Comment by Tigereye504** [comment]
looks good. Think you!

**Comment by mistermika06** [comment]
sorry, i don't know much about coding. where do i need to put this?

**Comment by Tigereye504** [comment]
this was a fix from quite a while ago. If you are looking to open your friends chest cavity, you will need to enable doing so on your minecraft server's config and each player's client's config

**Comment by DarkandVampy** [comment]
everyone has their configs set correctly, but its still not working. What should we do?

**Comment by Kait22Kait** [comment]
Hello. Me and my friends are using Aternos as a server hoster. Is there a way for you to help us with the same problem the other person is having? We would greatly appreciate it. The problem is that i dont know where to put the code you have put in the conversation. I don't know is it working for us or no. I am waiting for your response.

**Comment by mistermika06** [comment]
the fix worked for me.

**Pull request merged**
